# Read the Docs configuration file
version: 2

# Build documentation in the docs/ directory with Sphinx
sphinx:
  configuration: docs/conf.py
  fail_on_warning: true

# Optionally build your docs in additional formats such as PDF and ePub
formats:
  - pdf
  - epub

# Python requirements and package installation
python:
  install:
    - method: pip
      path: .
    - requirements: requirements.txt

# Configuración específica para el build
build:
  os: ubuntu-22.04
  tools:
    python: "3.10" # Especifica la versión de Python que deseas usar
  jobs:
    post_create_environment:
      - pip install --upgrade pip
      - pip install hatch
      - pip install build
    post_build:
      - hatch build